package sheng.zhong.project2.AST;

/* Generated By:JJTree: Do not edit this line. ASTAddPar.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=sheng.zhong.project2.AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAddPar extends SimpleNode {
  public ASTAddPar(int id) {
    super(id);
  }

  public ASTAddPar(Sheng p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7a9b1af8911de81ff9fc412cbae94e5b (do not edit this line) */
