package sheng.zhong.project2.AST;

/* Generated By:JJTree: Do not edit this line. ASTAssign.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=sheng.zhong.project2.AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAssign extends SimpleNode {
  public ASTAssign(int id) {
    super(id);
  }

  public ASTAssign(Sheng p, int id) {
    super(p, id);
  }
  public String toString() {
    return "Assign";
  }

}
/* JavaCC - OriginalChecksum=33a14dbf883341f33c3009a3db35fc4d (do not edit this line) */
