package sheng.zhong.project2.AST;

/* Generated By:JJTree: Do not edit this line. ASTAdd.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=sheng.zhong.project2.AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAdd extends SimpleNode {
  private String sign;
  public String type;

  public ASTAdd(int id) {
    super(id);
    type = NodeUtils.ADD;
  }

  public ASTAdd(Sheng p, int id) {
    super(p, id);
  }
  public void setSign(String sign) {
    this.sign = sign;
  }
  public String toString() {
    return sign;
  }
}
/* JavaCC - OriginalChecksum=6b70391e49e6bd39233ab0b42ec7028e (do not edit this line) */
