package sheng.zhong.project2.AST;

/* Generated By:JJTree: Do not edit this line. ASTBoolPar.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=sheng.zhong.project2.AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBoolPar extends SimpleNode {
  public ASTBoolPar(int id) {
    super(id);
  }

  public ASTBoolPar(Sheng p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=36f239d5f4f9b80f31f37c38011fabb0 (do not edit this line) */
