package sheng.zhong.project2.AST;

/* Generated By:JJTree: Do not edit this line. ASTId.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=sheng.zhong.project2.AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTId extends SimpleNode {
	 private String variableName;
  public ASTId(int id) {
    super(id);
  }

  public ASTId(Sheng p, int id) {
    super(p, id);
  }
	public void setName(String v) {
		variableName = v;
	}
	public String toString() {
	return variableName;
	}

}
/* JavaCC - OriginalChecksum=cadbf475733728e18efa9dc1e5f9df47 (do not edit this line) */
