package sheng.zhong.project2.AST;

/* Generated By:JJTree: Do not edit this line. ASTMult.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=sheng.zhong.project2.AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMult extends SimpleNode {
  public ASTMult(int id) {
    super(id);
  }

  public ASTMult(Sheng p, int id) {
    super(p, id);
  }
  public String toString() {
    return "*";
  }
}
/* JavaCC - OriginalChecksum=6f4896619d03aa4a9807d3e506e42b2d (do not edit this line) */
