package sheng.zhong.project2.AST;

/* Generated By:JJTree: Do not edit this line. ASTOr.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=sheng.zhong.project2.AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOr extends SimpleNode {
  public ASTOr(int id) {
    super(id);
  }

  public ASTOr(Sheng p, int id) {
    super(p, id);
  }
  public String toString() {
    return "or";
  }
}
/* JavaCC - OriginalChecksum=49ea1dbf9ad9d210ff317b20215be8ed (do not edit this line) */
