package sheng.zhong.project2.AST;

/* Generated By:JJTree: Do not edit this line. ASTSkip.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSkip extends SimpleNode {
  int label;
  public ASTSkip(int id) {
    super(id);
  }

  public ASTSkip(Sheng p, int id) {
    super(p, id);
  }
  public void setLabel (int label) {
    this.label = label;
  }
  public String toString() {
    return label + " Skip";
  }
}
/* JavaCC - OriginalChecksum=ba9f58f2f4fc85bfae3b4fad8e14ae30 (do not edit this line) */
