package sheng.zhong.project2.AST;

/* Generated By:JavaCC: Do not edit this line. ShengTreeConstants.java Version 6.0_1 */
public interface ShengTreeConstants
{
  public int JJTSTART = 0;
  public int JJTCOMMANDS = 1;
  public int JJTVOID = 2;
  public int JJTIF = 3;
  public int JJTWHILE = 4;
  public int JJTSKIP = 5;
  public int JJTASSIGN = 6;
  public int JJTADD = 7;
  public int JJTMULT = 8;
  public int JJTINT = 9;
  public int JJTADDPAR = 10;
  public int JJTOR = 11;
  public int JJTAND = 12;
  public int JJTBFACTOR = 13;
  public int JJTBLITERAL = 14;
  public int JJTBNOT = 15;
  public int JJTRELATION = 16;
  public int JJTBOOLPAR = 17;
  public int JJTID = 18;


  public String[] jjtNodeName = {
    "START",
    "Commands",
    "void",
    "If",
    "While",
    "Skip",
    "Assign",
    "Add",
    "Mult",
    "Int",
    "AddPar",
    "Or",
    "And",
    "BFactor",
    "BLiteral",
    "BNot",
    "Relation",
    "BoolPar",
    "Id",
  };
}
/* JavaCC - OriginalChecksum=0079fb1315f8fb2f5b5e892bdd49c964 (do not edit this line) */
