/* Generated By:JJTree: Do not edit this line. ASTBNot.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBNot extends SimpleNode {
  public ASTBNot(int id) {
    super(id);
  }

  public ASTBNot(Sheng p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ebe256649e28785933c10023681b274d (do not edit this line) */
