/* Generated By:JJTree: Do not edit this line. ASTBFactor.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBFactor extends SimpleNode {
  public ASTBFactor(int id) {
    super(id);
  }

  public ASTBFactor(Sheng p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=325433e6570fc5a36491217fe34474f5 (do not edit this line) */
