/* Generated By:JJTree: Do not edit this line. ASTCommands.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCommands extends SimpleNode {
  public ASTCommands(int id) {
    super(id);
  }

  public ASTCommands(Sheng p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d16feb7d50d203bbece9cade7302c323 (do not edit this line) */
