/* Generated By:JJTree: Do not edit this line. ASTOneCommand.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOneCommand extends SimpleNode {
  public ASTOneCommand(int id) {
    super(id);
  }

  public ASTOneCommand(Sheng p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=72666aac7cdd11a4d5c0e1a59ef74f3b (do not edit this line) */
