/* Generated By:JJTree: Do not edit this line. ASTRelation.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRelation extends SimpleNode {
  private String operator;
  public ASTRelation(int id) {
    super(id);
  }

  public ASTRelation(Sheng p, int id) {
    super(p, id);
  }
  public void setOperator(String operator) {
    this.operator = operator;
  }
  public String toString() {
    if (operator.equals("<")) {
      return "Less";
    } else if (operator.equals(">")) {
      return "Gre";
    } else if (operator.equals(">=")) {
      return "Gre=";
    } else if (operator.equals("<=")) {
      return "Less=";
    }
    return operator;
  }
}
/* JavaCC - OriginalChecksum=ef6128ca14564aebef085044d5d8d2fc (do not edit this line) */
