/* Generated By:JJTree: Do not edit this line. ASTSTART.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSTART extends SimpleNode {
  public ASTSTART(int id) {
    super(id);
  }

  public ASTSTART(Sheng p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c3864e8ddfe7a039b67e3efe13105daa (do not edit this line) */
