/* Generated By:JJTree&JavaCC: Do not edit this line. ShengConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ShengConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASSIGN = 5;
  /** RegularExpression Id. */
  int LINEEND = 6;
  /** RegularExpression Id. */
  int IF = 7;
  /** RegularExpression Id. */
  int THEN = 8;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int FI = 10;
  /** RegularExpression Id. */
  int WHILE = 11;
  /** RegularExpression Id. */
  int DO = 12;
  /** RegularExpression Id. */
  int OD = 13;
  /** RegularExpression Id. */
  int SKIP2 = 14;
  /** RegularExpression Id. */
  int INTEGER = 15;
  /** RegularExpression Id. */
  int BLITERALS = 16;
  /** RegularExpression Id. */
  int ROPERATOR = 17;
  /** RegularExpression Id. */
  int BNOT = 18;
  /** RegularExpression Id. */
  int AND = 19;
  /** RegularExpression Id. */
  int OR = 20;
  /** RegularExpression Id. */
  int IDENTIFIERS = 21;
  /** RegularExpression Id. */
  int LETTER = 22;
  /** RegularExpression Id. */
  int DIGIT = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\":=\"",
    "\";\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"fi\"",
    "\"while\"",
    "\"do\"",
    "\"od\"",
    "\"skip\"",
    "<INTEGER>",
    "<BLITERALS>",
    "<ROPERATOR>",
    "\"not\"",
    "\"and\"",
    "\"or\"",
    "<IDENTIFIERS>",
    "<LETTER>",
    "<DIGIT>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
  };

}
